# Generated by Django 5.0.2 on 2024-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0002_employee_hierarchy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\HP\\PycharmProjects\\GazBrom\\media\\images'),
        ),
    ]
