version: '3.8'

services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - employees_postgres_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_DB: employees_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "54322:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  gazbromapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gazbromapp
    command: >
      sh -c '/wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    volumes:
      - .:/GazBrom_empl  # Монтирование проекта в контейнер
      - ./GazBrom_empl/media:/gazbromapp/media  # Монтирование директории media на хосте в media в контейнере
    environment:
      - DATABASE_NAME=employees_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  employees_postgres_data:
